// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// simulateTumorcpp
Rcpp::List simulateTumorcpp(Rcpp::List input);
RcppExport SEXP _SITH_simulateTumorcpp(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(simulateTumorcpp(input));
    return rcpp_result_gen;
END_RCPP
}
// simulateTumorMTBPcpp
Rcpp::List simulateTumorMTBPcpp(Rcpp::List input);
RcppExport SEXP _SITH_simulateTumorMTBPcpp(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type input(inputSEXP);
    rcpp_result_gen = Rcpp::wrap(simulateTumorMTBPcpp(input));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SITH_simulateTumorcpp", (DL_FUNC) &_SITH_simulateTumorcpp, 1},
    {"_SITH_simulateTumorMTBPcpp", (DL_FUNC) &_SITH_simulateTumorMTBPcpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_SITH(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
