# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulate_tumor <- function(input) {
    .Call(`_SITH_simulate_tumor`, input)
}

simulateTumorMTBPcpp <- function(input) {
    .Call(`_SITH_simulateTumorMTBPcpp`, input)
}

