# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulateTumorcpp <- function(input) {
    .Call(`_SITH_simulateTumorcpp`, input)
}

simulateTumorUDTcpp <- function(input) {
    .Call(`_SITH_simulateTumorUDTcpp`, input)
}

